// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourReservationAPI.Data;

namespace TourReservationAPI.Migrations
{
    [DbContext(typeof(GuideDbContext))]
    [Migration("20200326182546_4.0")]
    partial class _40
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TourReservationAPI.Data.Guide", b =>
                {
                    b.Property<Guid>("guideID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgeLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("RezervationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("guideID");

                    b.HasIndex("RezervationID");

                    b.ToTable("Guides");
                });

            modelBuilder.Entity("TourReservationAPI.Data.Rezervation", b =>
                {
                    b.Property<Guid>("RezervationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GuideId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonAge")
                        .HasColumnType("int");

                    b.Property<DateTime>("RezervationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RezervationID");

                    b.ToTable("Rezervations");
                });

            modelBuilder.Entity("TourReservationAPI.Data.Guide", b =>
                {
                    b.HasOne("TourReservationAPI.Data.Rezervation", null)
                        .WithMany("Guides")
                        .HasForeignKey("RezervationID");
                });
#pragma warning restore 612, 618
        }
    }
}
